name: Deploy

on:
  workflow_run:
    workflows: [ "Docker" ]
    types: [ completed ]
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: read
      id-token: write
    
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/containers/twitch-stream-hunter
            docker compose down api
            docker pull ghcr.io/khiemnguyen15/twitch-stream-hunter-api:master
            docker compose up api -d
